---
apiVersion: kafka.stackable.tech/v1alpha1
kind: KafkaCluster
metadata:
  name: lukewarm-kafka
spec:
  image:
    productVersion: "3.7.1"
  clusterConfig:
    zookeeperConfigMapName: lukewarm-kafka-znode
  brokers:
    roleGroups:
      default:
        replicas: 1
        config:
          resources:
            cpu:
              min: "250m"
              max: "1000m"
            memory:
              limit: "1Gi"
            storage:
              logDirs:
                capacity: 10Gi
