auth:
  username: hive
  password: hive
  database: metastore

primary:
  resources:
    requests:
      memory: 256Mi
      cpu: 250m
    limits:
      memory: 512Mi
      cpu: 500m

  persistence:
    enabled: true
    size: 8Gi
